canvas = document.getElementById("c1");
ctx = canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle="blue";
ctx.lineWidth=3;
ctx.arc(200,200,40,0,2*Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle="red";
ctx.lineWidth=1;
ctx.rect(150, 143, 430, 200, 2*Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle="orange";
ctx.lineWidth=3;
ctx.arc(240,260,40,0,2*Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle="black";
ctx.lineWidth=3;
ctx.arc(290,200,40,0,2*Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle="green";
ctx.lineWidth=3;
ctx.arc(340,260,40,0,2*Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle="red";
ctx.lineWidth=3;
ctx.arc(380,200,40,0,2*Math.PI);
ctx.stroke();
